/*
 * This source file was generated by the Gradle 'init' task
 */
package io.cheonkyu;

import io.cheonkyu.mini.spring.boot.SpringApplication;

public class MainApplication {
    public static void main(String[] args) {
        final var app = new SpringApplication();
        app.run();
        // System.out.println(new MainApplication().getGreeting());
    }
}
